# Generated by Django 3.2.7 on 2021-09-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Категория еды',
                'verbose_name_plural': 'Категории еды',
            },
        ),
    ]
