# Generated by Django 3.2.7 on 2021-09-04 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('price', models.CharField(max_length=15, verbose_name='Стоимость')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categoriedish', verbose_name='Категория еды')),
            ],
        ),
    ]
