# Generated by Django 3.2.7 on 2021-09-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание блюда'),
            preserve_default=False,
        ),
    ]
