# Generated by Django 3.2.7 on 2021-09-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='static/img', verbose_name='Фото')),
                ('name_chef', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('about_chef', models.CharField(max_length=150, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Повор',
                'verbose_name_plural': 'Повора',
            },
        ),
    ]
