# Generated by Django 3.2.7 on 2021-09-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя категории')),
                ('slug', models.SlugField(max_length=25, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('small_image', models.ImageField(upload_to='static/gallery', verbose_name='Маленькая картинка')),
                ('large_image', models.ImageField(upload_to='static/gallery', verbose_name='Большая картинка')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.categorie', verbose_name='Категория')),
            ],
        ),
    ]
